# Generated by Django 6.0.2 on 2026-02-13 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('system', '系统通知'), ('todo', '待办提醒'), ('approval', '审批通知'), ('inventory', '盘点通知')], default='system', max_length=32, verbose_name='通知类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('related_type', models.CharField(blank=True, max_length=32, verbose_name='关联类型')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知消息',
                'verbose_name_plural': '通知消息',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='待办标题')),
                ('content', models.TextField(blank=True, verbose_name='待办内容')),
                ('todo_type', models.CharField(choices=[('personal', '个人待办'), ('asset_approval', '资产审批'), ('maintenance', '维修审批'), ('inventory', '盘点任务'), ('transfer', '资产调拨')], default='personal', max_length=32, verbose_name='待办类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=16, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('remind_time', models.DateTimeField(blank=True, null=True, verbose_name='提醒时间')),
                ('related_type', models.CharField(blank=True, max_length=32, verbose_name='关联类型')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='待办人')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_todos', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
                'db_table': 'todos',
                'ordering': ['-created_at'],
            },
        ),
    ]
