# Generated by Django 6.0.2 on 2026-02-13 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='计划名称')),
                ('plan_no', models.CharField(max_length=32, unique=True, verbose_name='计划编号')),
                ('plan_type', models.CharField(choices=[('full', '全盘'), ('sample', '抽盘'), ('dynamic', '动态盘点')], max_length=20, verbose_name='计划类型')),
                ('scope', models.TextField(blank=True, verbose_name='盘点范围描述')),
                ('location_ids', models.TextField(blank=True, verbose_name='涉及位置ID列表')),
                ('category_ids', models.TextField(blank=True, verbose_name='涉及分类ID列表')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待执行'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('scheduled_start', models.DateTimeField(verbose_name='计划开始时间')),
                ('scheduled_end', models.DateTimeField(verbose_name='计划结束时间')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '盘点计划',
                'verbose_name_plural': '盘点计划',
                'db_table': 'inventory_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=32, unique=True, verbose_name='任务编号')),
                ('device_count', models.IntegerField(default=0, verbose_name='应盘数量')),
                ('checked_count', models.IntegerField(default=0, verbose_name='已盘数量')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '执行中'), ('completed', '已完成'), ('verified', '已审核')], default='pending', max_length=20, verbose_name='状态')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_tasks', to='assets.assetcategory', verbose_name='盘点分类')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_tasks', to='assets.assetlocation', verbose_name='盘点位置')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inventory.inventoryplan', verbose_name='盘点计划')),
            ],
            options={
                'verbose_name': '盘点任务',
                'verbose_name_plural': '盘点任务',
                'db_table': 'inventory_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_status', models.CharField(blank=True, max_length=20, verbose_name='盘点时设备状态')),
                ('location_status', models.CharField(choices=[('in_place', '在位'), ('moved', '搬离'), ('not_found', '未找到')], max_length=20, verbose_name='位置状态')),
                ('asset_status', models.CharField(choices=[('normal', '正常'), ('damaged', '损坏'), ('lost', '丢失')], default='normal', max_length=20, verbose_name='资产状态')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('photo_path', models.CharField(blank=True, max_length=256, verbose_name='现场照片路径')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='盘点时间')),
                ('source', models.CharField(choices=[('manual', '手工盘点'), ('wechat', '微信扫码')], default='manual', max_length=20, verbose_name='来源')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to=settings.AUTH_USER_MODEL, verbose_name='盘点人')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='assets.device', verbose_name='设备')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.inventorytask', verbose_name='盘点任务')),
            ],
            options={
                'verbose_name': '盘点记录',
                'verbose_name_plural': '盘点记录',
                'db_table': 'inventory_records',
                'ordering': ['-checked_at'],
            },
        ),
    ]
