# Generated by Django 5.2.12 on 2026-04-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_alter_consumable_options_remove_consumable_unit_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='photo',
            field=models.ImageField(blank=True, upload_to='inventory_photos/', verbose_name='现场照片'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='is_fixed_only',
            field=models.BooleanField(default=False, verbose_name='仅固资在账'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='任务名称'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划结束时间'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='task_type',
            field=models.CharField(choices=[('full', '全盘'), ('sample', '抽盘'), ('dynamic', '动态盘点')], default='full', max_length=20, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='location_status',
            field=models.CharField(choices=[('in_place', '在位'), ('moved', '搬离'), ('not_found', '未找到')], default='in_place', max_length=20, verbose_name='位置状态'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='source',
            field=models.CharField(choices=[('manual', '手工盘点'), ('scan', '扫码盘点'), ('wechat', '微信扫码')], default='manual', max_length=20, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='inventorytask',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='inventory.inventoryplan', verbose_name='盘点计划'),
        ),
        migrations.AlterField(
            model_name='inventorytask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('in_progress', '执行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='InventoryTaskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待盘点'), ('checked', '已盘点')], default='pending', max_length=20, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='盘点时间')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_task_devices', to='assets.device', verbose_name='设备')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_devices', to='inventory.inventorytask', verbose_name='盘点任务')),
            ],
            options={
                'verbose_name': '盘点任务设备',
                'verbose_name_plural': '盘点任务设备',
                'db_table': 'inventory_task_devices',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('task', 'device')},
            },
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='task_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='inventory.inventorytaskdevice', verbose_name='任务设备关联'),
        ),
    ]
