"""Update AssetLocation model for parks and buildings hierarchy

Revision ID: 649dce7f7fa7
Revises: 
Create Date: 2025-04-17 17:52:39.766989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649dce7f7fa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_locations', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('asset_locations', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('asset_locations', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('asset_locations', sa.Column('is_multi_floor', sa.Boolean(), nullable=True))
    op.add_column('asset_locations', sa.Column('floor_count', sa.Integer(), nullable=True))
    op.add_column('asset_locations', sa.Column('floor_names', sa.Text(), nullable=True))
    op.add_column('asset_locations', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_locations', 'sort_order')
    op.drop_column('asset_locations', 'floor_names')
    op.drop_column('asset_locations', 'floor_count')
    op.drop_column('asset_locations', 'is_multi_floor')
    op.drop_column('asset_locations', 'height')
    op.drop_column('asset_locations', 'width')
    op.drop_column('asset_locations', 'type')
    # ### end Alembic commands ###
