# Generated by Django 6.0.2 on 2026-02-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='企业名称')),
                ('short_name', models.CharField(blank=True, max_length=64, verbose_name='简称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='企业编码')),
                ('logo', models.ImageField(blank=True, upload_to='org_logos/', verbose_name='Logo')),
                ('contact_person', models.CharField(blank=True, max_length=64, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='地址')),
                ('website', models.CharField(blank=True, max_length=128, verbose_name='网站')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=64, unique=True, verbose_name='配置键')),
                ('config_value', models.TextField(blank=True, verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('int', '整数'), ('boolean', '布尔值'), ('json', 'JSON')], default='string', max_length=16, verbose_name='值类型')),
                ('config_group', models.CharField(choices=[('basic', '基础设置'), ('security', '安全设置'), ('asset', '资产设置'), ('wechat', '微信设置')], default='basic', max_length=32, verbose_name='配置分组')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='说明')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统级配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configs',
                'ordering': ['config_group', 'id'],
            },
        ),
    ]
