# Generated by Django 5.2.12 on 2026-03-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='config_group',
            field=models.CharField(choices=[('basic', '基础设置'), ('security', '安全设置'), ('asset', '资产设置')], default='basic', max_length=32, verbose_name='配置分组'),
        ),
    ]
