# Generated by Django 5.2.12 on 2026-04-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_systemconfig_config_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='options',
            field=models.TextField(blank=True, verbose_name='选项(JSON)'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value_type',
            field=models.CharField(choices=[('string', '字符串'), ('int', '整数'), ('boolean', '布尔值'), ('json', 'JSON'), ('select', '下拉选择')], default='string', max_length=16, verbose_name='值类型'),
        ),
    ]
