# Generated by Django 5.2.12 on 2026-04-01 05:59

from django.db import migrations


def create_timezone_config(apps, schema_editor):
    SystemConfig = apps.get_model('settings', 'SystemConfig')
    
    timezone_options = [
        ["Asia/Shanghai", "亚洲/上海 (UTC+8)"],
        ["Asia/Tokyo", "亚洲/东京 (UTC+9)"],
        ["Asia/Singapore", "亚洲/新加坡 (UTC+8)"],
        ["Asia/Hong_Kong", "亚洲/香港 (UTC+8)"],
        ["Asia/Seoul", "亚洲/首尔 (UTC+9)"],
        ["Asia/Bangkok", "亚洲/曼谷 (UTC+7)"],
        ["Asia/Dubai", "亚洲/迪拜 (UTC+4)"],
        ["Europe/London", "欧洲/伦敦 (UTC+0)"],
        ["Europe/Paris", "欧洲/巴黎 (UTC+1)"],
        ["Europe/Berlin", "欧洲/柏林 (UTC+1)"],
        ["Europe/Moscow", "欧洲/莫斯科 (UTC+3)"],
        ["America/New_York", "美国/纽约 (UTC-5)"],
        ["America/Los_Angeles", "美国/洛杉矶 (UTC-8)"],
        ["America/Chicago", "美国/芝加哥 (UTC-6)"],
        ["Australia/Sydney", "澳大利亚/悉尼 (UTC+10)"],
        ["Pacific/Auckland", "新西兰/奥克兰 (UTC+12)"],
        ["UTC", "协调世界时 (UTC+0)"],
    ]
    
    import json
    SystemConfig.objects.update_or_create(
        config_key='timezone',
        defaults={
            'config_value': 'Asia/Shanghai',
            'value_type': 'select',
            'config_group': 'basic',
            'description': '时区设置',
            'options': json.dumps(timezone_options, ensure_ascii=False),
            'is_system': False,
        }
    )


def remove_timezone_config(apps, schema_editor):
    SystemConfig = apps.get_model('settings', 'SystemConfig')
    SystemConfig.objects.filter(config_key='timezone').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_systemconfig_options_alter_systemconfig_value_type'),
    ]

    operations = [
        migrations.RunPython(create_timezone_config, remove_timezone_config),
    ]
