# Generated by Django 5.2.12 on 2026-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_add_timezone_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['config_group', 'sort', 'id'], 'verbose_name': '系统配置', 'verbose_name_plural': '系统配置'},
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
