# Generated by Django 6.0.2 on 2026-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocation',
            name='floor_count',
            field=models.IntegerField(default=1, verbose_name='楼层数'),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='room_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='房间编码'),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='floor_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='楼层编码'),
        ),
    ]
