# Generated by Django 6.0.2 on 2026-02-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_add_floor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocation',
            name='default_doorstop_width',
            field=models.FloatField(default=15, verbose_name='默认门垛宽度'),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='default_snap_enabled',
            field=models.BooleanField(default=True, verbose_name='默认启用吸附'),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='default_snap_threshold',
            field=models.FloatField(default=10, verbose_name='默认吸附阈值'),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='grid_size',
            field=models.IntegerField(default=50, verbose_name='网格大小'),
        ),
        migrations.AddField(
            model_name='mapelement',
            name='auto_doorstop',
            field=models.BooleanField(default=True, verbose_name='自动生成门垛'),
        ),
        migrations.AddField(
            model_name='mapelement',
            name='door_direction',
            field=models.CharField(choices=[('right', '右开'), ('left', '左开'), ('sliding', '推拉')], default='right', max_length=10, verbose_name='门开方向'),
        ),
        migrations.AddField(
            model_name='mapelement',
            name='door_open_angle',
            field=models.IntegerField(default=90, verbose_name='门打开角度'),
        ),
        migrations.AddField(
            model_name='mapelement',
            name='door_width',
            field=models.FloatField(default=60, verbose_name='门宽'),
        ),
        migrations.AddField(
            model_name='mapelement',
            name='doorstop_width',
            field=models.FloatField(default=15, verbose_name='门垛宽度'),
        ),
        migrations.AddField(
            model_name='mapelement',
            name='snap_enabled',
            field=models.BooleanField(default=True, verbose_name='启用吸附'),
        ),
        migrations.AddField(
            model_name='mapelement',
            name='snap_threshold',
            field=models.FloatField(default=10, verbose_name='吸附阈值'),
        ),
    ]
