# Generated by Django 6.0.2 on 2026-02-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_map_editor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocation',
            name='basement_count',
            field=models.IntegerField(default=0, verbose_name='地下楼层数'),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='has_basement',
            field=models.BooleanField(default=False, verbose_name='包含地下楼层'),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='floor_count',
            field=models.IntegerField(default=1, verbose_name='地上楼层数'),
        ),
    ]
