# Generated by Django 6.0.2 on 2026-02-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_basement_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocation',
            name='has_rooftop',
            field=models.BooleanField(default=False, verbose_name='包含天台'),
        ),
    ]
