# Generated by Django 6.0.2 on 2026-02-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_rooftop_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlocation',
            name='has_basement',
        ),
    ]
