# Generated by Django 6.0.2 on 2026-02-13 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_has_basement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAreaBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_points', models.TextField(verbose_name='区域坐标点(JSON)')),
                ('area_color', models.CharField(default='#3498db', max_length=7, verbose_name='区域颜色')),
                ('area_name', models.CharField(max_length=64, verbose_name='区域名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_bindings', to='assets.assetlocation', verbose_name='4级位置')),
                ('parent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_area_bindings', to='assets.assetlocation', verbose_name='3级位置')),
            ],
            options={
                'verbose_name': '位置区域绑定',
                'verbose_name_plural': '位置区域绑定',
                'db_table': 'location_area_bindings',
            },
        ),
    ]
