# Generated by Django 5.2.12 on 2026-03-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_add_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(max_length=32, verbose_name='分类编码'),
        ),
    ]
