# Generated by Django 5.2.12 on 2026-03-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_assetcategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapelement',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='标签文字'),
        ),
    ]
