# Generated by Django 5.2.12 on 2026-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_add_label_to_map_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapelement',
            name='element_type',
            field=models.CharField(choices=[('wall', '墙'), ('door', '门'), ('window', '窗'), ('rect', '矩形'), ('desk', '工位'), ('workstation', '工位'), ('region', '区域'), ('text', '文字'), ('equipment', '设备')], max_length=20, verbose_name='元素类型'),
        ),
    ]
