# Generated by Django 5.2.12 on 2026-03-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_add_element_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlocation',
            name='grid_size',
            field=models.IntegerField(default=30, verbose_name='网格大小'),
        ),
    ]
