# Generated by Django 5.2.12 on 2026-03-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_update_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('size_type', models.CharField(choices=[('40x60', '40×60mm'), ('50x80', '50×80mm'), ('custom', '自定义尺寸')], default='50x80', max_length=20, verbose_name='标签尺寸')),
                ('width', models.IntegerField(default=50, verbose_name='宽度(mm)')),
                ('height', models.IntegerField(default=80, verbose_name='高度(mm)')),
                ('fields_config', models.JSONField(default=list, verbose_name='字段配置')),
                ('layout_config', models.JSONField(default=dict, verbose_name='排版配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签模板',
                'verbose_name_plural': '标签模板',
                'db_table': 'label_templates',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id'], 'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterField(
            model_name='device',
            name='secret_level',
            field=models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('confidential', '秘密'), ('secret', '机密'), ('top_secret', '绝密'), ('commercial_secret', '商密')], default='public', max_length=20, verbose_name='密级'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('normal', '使用'), ('fault', '故障'), ('scrapped', '报废'), ('unused', '闲置')], default='normal', max_length=20, verbose_name='设备状态'),
        ),
    ]
