# Generated by Django 5.2.12 on 2026-04-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_label_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='照片更新时间'),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('assign', '分配'), ('transfer', '转移'), ('repair', '维修'), ('scrap', '报废'), ('revoke', '回收')], max_length=20, verbose_name='操作'),
        ),
    ]
