# Generated by Django 5.2.12 on 2026-04-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_device_photo_updated_at_alter_assetlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocation',
            name='area_points',
            field=models.TextField(blank=True, verbose_name='区域坐标点(JSON)'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_workstations', to='assets.assetlocation', verbose_name='所属区域'),
        ),
    ]
