# Generated by Django 5.2.12 on 2026-04-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_assetlocation_area_points_workstation_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fault_reason',
            field=models.TextField(blank=True, verbose_name='故障原因'),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('assign', '分配'), ('transfer', '转移'), ('repair', '维修'), ('scrap', '报废'), ('revoke', '回收'), ('fault', '报障')], max_length=20, verbose_name='操作'),
        ),
    ]
