# Generated by Django 5.2.12 on 2026-04-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_device_fault_reason_alter_assetlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='scrap_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报废时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='scrap_pre_scrap_data',
            field=models.TextField(blank=True, verbose_name='报废前关联数据'),
        ),
    ]
