# Generated by Django 5.2.12 on 2026-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_device_scrap_date_device_scrap_pre_scrap_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='asset_card_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='卡片编号'),
        ),
        migrations.AddField(
            model_name='software',
            name='asset_no',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='资产编号'),
        ),
        migrations.AddField(
            model_name='software',
            name='device_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='software',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='固资在账'),
        ),
        migrations.AddField(
            model_name='software',
            name='serial_no',
            field=models.CharField(blank=True, max_length=128, verbose_name='序列号'),
        ),
    ]
