# Generated by Django 5.2.12 on 2026-04-07 01:09

import django.db.models.deletion
from django.db import migrations, models


def create_default_software_fields(apps, schema_editor):
    SoftwareField = apps.get_model('assets', 'SoftwareField')
    
    default_fields = [
        {'name': '软件名称', 'field_key': 'name', 'sort': 1, 'is_visible': True, 'field_type': 'text', 'is_system': True},
        {'name': '资产编号', 'field_key': 'asset_no', 'sort': 2, 'is_visible': True, 'field_type': 'text', 'is_system': True},
        {'name': '编号', 'field_key': 'device_no', 'sort': 3, 'is_visible': True, 'field_type': 'text', 'is_system': True},
        {'name': '版本', 'field_key': 'version', 'sort': 4, 'is_visible': True, 'field_type': 'text', 'is_system': True},
        {'name': '供应商', 'field_key': 'vendor', 'sort': 5, 'is_visible': True, 'field_type': 'text', 'is_system': True},
        {'name': '授权类型', 'field_key': 'license_type', 'sort': 6, 'is_visible': True, 'field_type': 'select', 'is_system': True},
        {'name': '授权数量', 'field_key': 'license_count', 'sort': 7, 'is_visible': True, 'field_type': 'number', 'is_system': True},
        {'name': '价格', 'field_key': 'price', 'sort': 8, 'is_visible': True, 'field_type': 'number', 'is_system': True},
        {'name': '购买日期', 'field_key': 'purchase_date', 'sort': 9, 'is_visible': False, 'field_type': 'date', 'is_system': True},
        {'name': '到期日期', 'field_key': 'expire_date', 'sort': 10, 'is_visible': False, 'field_type': 'date', 'is_system': True},
        {'name': '固资在账', 'field_key': 'is_fixed', 'sort': 11, 'is_visible': True, 'field_type': 'checkbox', 'is_system': True},
        {'name': '卡片编号', 'field_key': 'asset_card_no', 'sort': 12, 'is_visible': True, 'field_type': 'text', 'is_system': True},
        {'name': '描述', 'field_key': 'description', 'sort': 13, 'is_visible': True, 'field_type': 'textarea', 'is_system': True},
        {'name': '创建时间', 'field_key': 'created_at', 'sort': 14, 'is_visible': False, 'field_type': 'datetime', 'is_system': True},
        {'name': '更新时间', 'field_key': 'updated_at', 'sort': 15, 'is_visible': False, 'field_type': 'datetime', 'is_system': True},
    ]
    
    for field_data in default_fields:
        SoftwareField.objects.create(**field_data)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_software_asset_card_no_software_asset_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='字段名称')),
                ('field_key', models.CharField(max_length=32, unique=True, verbose_name='字段键名')),
                ('field_type', models.CharField(choices=[('text', '文本'), ('textarea', '多行文本'), ('number', '数字'), ('select', '下拉选择'), ('multi_select', '多选'), ('date', '日期'), ('datetime', '日期时间'), ('checkbox', '复选框'), ('file', '文件上传')], default='text', max_length=20, verbose_name='字段类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('options', models.TextField(blank=True, verbose_name='选项(JSON)')),
                ('default_value', models.CharField(blank=True, max_length=256, verbose_name='默认值')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统字段')),
            ],
            options={
                'verbose_name': '软件字段',
                'verbose_name_plural': '软件字段',
                'db_table': 'software_fields',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='software',
            name='license_type',
            field=models.CharField(choices=[('perpetual', '永久授权'), ('subscription', '订阅'), ('open', '开源'), ('free', '免费'), ('trial', '试用')], default='perpetual', max_length=32, verbose_name='授权类型'),
        ),
        migrations.CreateModel(
            name='SoftwareFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='字段值')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.softwarefield', verbose_name='字段')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='assets.software', verbose_name='软件')),
            ],
            options={
                'verbose_name': '软件字段值',
                'verbose_name_plural': '软件字段值',
                'db_table': 'software_field_values',
            },
        ),
        migrations.RunPython(create_default_software_fields, migrations.RunPython.noop),
    ]
