# Generated by Django 5.2.12 on 2026-04-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_softwarefield_alter_software_license_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='serial_no',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='序列号'),
        ),
    ]
