# Generated by Django 5.2.12 on 2026-04-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_alter_software_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='asset_card_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='卡片编号'),
        ),
        migrations.AlterField(
            model_name='software',
            name='asset_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='software',
            name='device_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='software',
            name='vendor',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='版本'),
        ),
    ]
