# Generated by Django 5.2.12 on 2026-04-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_alter_software_asset_card_no_alter_software_asset_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
