# Generated by Django 5.2.12 on 2026-04-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_software_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefield',
            name='is_card_visible',
            field=models.BooleanField(default=False, verbose_name='卡片显示'),
        ),
        migrations.AlterField(
            model_name='devicefield',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='列表显示'),
        ),
    ]
