# Generated by Django 5.2.12 on 2026-04-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_devicefield_is_card_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarefield',
            name='is_card_visible',
            field=models.BooleanField(default=False, verbose_name='卡片显示'),
        ),
        migrations.AlterField(
            model_name='softwarefield',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='列表显示'),
        ),
    ]
