# Generated by Django 5.2.12 on 2026-04-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_softwarefield_is_card_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='服务名称')),
                ('service_type', models.CharField(blank=True, max_length=64, verbose_name='服务类型')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='服务价格')),
                ('start_date', models.DateField(verbose_name='服务开始日期')),
                ('end_date', models.DateField(verbose_name='服务结束日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务合同',
                'verbose_name_plural': '服务合同',
                'db_table': 'service_contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
