# Generated by Django 5.2.12 on 2026-04-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_servicecontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumable',
            name='code',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='price',
        ),
    ]
