# Generated by Django 5.2.12 on 2026-04-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_remove_consumable_code_remove_consumable_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ['name'], 'verbose_name': '耗材物资', 'verbose_name_plural': '耗材物资'},
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='unit',
        ),
        migrations.AddField(
            model_name='consumable',
            name='applicable_models',
            field=models.CharField(blank=True, max_length=128, verbose_name='适用机型'),
        ),
    ]
