# Generated by Django 5.2.12 on 2026-05-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_alter_consumable_options_remove_consumable_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='size_type',
            field=models.CharField(choices=[('40x60', '40×60mm'), ('45x70', '45×70mm'), ('50x80', '50×80mm'), ('custom', '自定义尺寸')], default='50x80', max_length=20, verbose_name='标签尺寸'),
        ),
    ]
