# Generated by Django 6.0.2 on 2026-02-13 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('assign', '分配'), ('transfer', '转移'), ('repair', '维修'), ('scrap', '报废')], max_length=20, verbose_name='操作')),
                ('field_name', models.CharField(blank=True, max_length=64, verbose_name='变动字段')),
                ('old_value', models.TextField(blank=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sys_logs', to='assets.device', verbose_name='设备')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '资产变动日志',
                'verbose_name_plural': '资产变动日志',
                'db_table': 'asset_sys_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='asset_sys_l_created_114d51_idx'), models.Index(fields=['device', '-created_at'], name='asset_sys_l_device__376be4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='操作账号')),
                ('log_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('operation', '操作'), ('error', '错误'), ('security', '安全')], max_length=32, verbose_name='日志类型')),
                ('action', models.CharField(max_length=128, verbose_name='操作动作')),
                ('module', models.CharField(blank=True, max_length=64, verbose_name='操作模块')),
                ('method', models.CharField(blank=True, max_length=32, verbose_name='请求方法')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_url', models.CharField(blank=True, max_length=512, verbose_name='请求URL')),
                ('request_data', models.TextField(blank=True, verbose_name='请求参数')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='system_logs_created_9fcafe_idx'), models.Index(fields=['log_type'], name='system_logs_log_typ_c8f71a_idx')],
            },
        ),
    ]
